version: '3'

# volumes:
#   bundle:
#   db:


services:

  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    entrypoint: ./rails/bin/docker-entrypoint

  # db:
  #   image: nouchka/sqlite3:latest
  #   volumes:
  #     - db:/root/db
  #   stdin_open: true
  #   tty: true

  # web: &rails
  #   build:
  #     context: ./rails
  #     dockerfile: Dockerfile
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
  #   volumes:
  #     - .:/rails
  #     - bundle:/usr/local/bundle
  #     - ./node_modules:/app/node_modules
  #   tmpfs: /rails/tmp
  #   depends_on:
  #     - db
  #   # env_file: /rails/app.env
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - "3000:3000"

  # ///////this is the "good one"
  # rails:
  #   build:
  #     context: ./rails
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - RAILS_ENV=development
  #   depends_on:
  #     - database

  # database:
  #   image: busybox
  #   volumes:
  #     - ./db:/rails/db
  #   command: tail -f /dev/null

  client:
    container_name: client-c
    image: client-i
    build:
      context: ./client
    ports:
      - 8080:80
    # version: '3'
    # services:
    #   api:
    #     build: api
    #     image: rails-api
    #     command: bash -c "bundle exec rails s -p 4000 -b '0.0.0.0'"
    #     stdin_open: true
    #     tty: true
    #     ports:
    #       - "4000:4000"
    #     working_dir: /api
    #     volumes:
    #       - ./api:/api
    #     depends_on:
    #       - db
    #   client:
    #     build: client
    #     image: react-client
    #     command: sh -c "npm install && npm run dev"
    #     ports:
    #       - "3000:3000"
    #     working_dir: /client
    #     volumes:
    #       - ./client:/client
    #   db:
    # image: nouchka/sqlite3:latest
    #     stdin_open: true
    #     tty: true
    #     volumes:
    #       - ./db/:/root/db/
    # volumes:
    #   db-data:
