production:
  secret_key_base: <% ENV["SECRET_KEY_BASE"] %>
  aws_secert: abcde
  some_password: abcde

development:
  secret_key_base: static_secret_key
  aws_secret: abced

test:
  secret_key_base: static_test_secret_key