workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build


orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    working_directory: ~/rails
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: hello
          command: echo hello
      # - run:
      #     name: build-docker-image
      #     command: docker build -t $IMAGE_NAME:latest . --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
      # - run:
      #     name: publish-docker-image
      #     command: docker push $IMAGE_NAME
      # - run:
      #     name: run-docker-image
      #     command: docker run -p 3000:3000 -d $IMAGE_NAME
  deploy:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - run:
          name: world
          command: echo world
          # ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export CONTAINER_NAME=\"$CONTAINER_NAME\"; export IMAGE_NAME=\"$IMAGE_NAME\"; rm -rf TodoList/; git clone https://github.com/VMaderaAlbors/Articles-rails.git; source TodoList/deploy.sh"